openapi: '3.0.2'
info:
  title: Uno Online
  version: '1.0'
servers:
  - url: https://localhost:3000
basePath: /
paths:
  /users:
    get:
      sumary: Get a list of users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Bad Request


components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string

# router.get("users.list", "/", async(ctx) => {
#   try {
#     const users = await ctx.orm.User.findAll();
#     ctx.body = users;
#     ctx.status = 200;
#   } catch(error) {
#     ctx.body = error;
#     ctx.status = 400;
#   }
# })

# router.post("users.create", "/signup", async(ctx) => {
#   try {
#     const user = await ctx.orm.User.create(ctx.request.body);
#     ctx.body = user;
#     ctx.status = 201;
#   } catch(error) {
#     ctx.body = error;
#     ctx.status = 400;
#   }
# })